[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "footstats-cli"
version = "0.1.2"
description = "Football Stats Scraper - Footstats CLI"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.13"
license = "MIT"
dependencies = [
    "annotated-doc>=0.0.4",
    "beautifulsoup4>=4.14.3",
    "python-dotenv>=1.2.2",
    "readchar>=4.2.2",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "shellingham>=1.5.4",
    "typer>=0.26.4",
]
authors = [
    {name = "Jose marin", email = "jamrin2409@gmail.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "Programming Language :: Python",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
]

[project.optional-dependencies]
dev = [
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pytest>=9.0.3",
]

[project.urls]
Repository = "https://github.com/Marin2409/footstats-cli"

[project.scripts]
footstats = "src.cli.main:app"

[tool.hatch.build.targets.wheel]
packages = ["src"]
